### ISSUE TITLE
Map- card shows wrong zoom level in pop-up-card

### ISSUE THREAD

**Issue by enedberg** [Clooos/Bubble-Card#1334]
**Describe the bug**  
I have a pop-up-card with a map card. The map works fine as a separate card, but in a pop-up it show with the wrong zoom level, completely zoomed out. I tried with background_update: true , tried placing the map inside another container (horizontal-stack), tried with no default-zoom, but the problem persists. I have also cleared my cache. Same problem on Mac and iPhone (browser and HA-app).

I have three other pop-up on the same dashboard, they work fine. I use sections on this dashboard and it is my default mobile dashboard.

I tried the same pop-up with the map on a different dashboard (using Masonry layout). It worked as expected there. Also, if I show only one entity on the map card it works as expected.

**To Reproduce**  
1. On a dashboard using sections: Add a vertical stack with a pop-up-card and a map card
2. Add more than one entity to the map
3. Click on whatever button opens the pop-up
4. Map is zoomed out

The map is shown correctly in the editor, and it _sometimes_ opens correctly after a refresh 

**Expected behavior**  
The map card should open with the correct zoom level

**Screenshots**  

<img width="605" alt="Image" src="https://github.com/user-attachments/assets/5199a1ff-84f0-4b0c-b17f-b8cdcbe7b08c" />

**YAML**  
This is the code for the vertical-stack with pop-up and map

```yaml
type: vertical-stack
cards:
  - type: custom:bubble-card
    card_type: pop-up
    hash: "#pop-up-maps"
    show_header: false
    auto_close: "15000"
    background_update: false
  - type: map
    entities:
      - entity: person.e
      - entity: person.y
      - entity: person.i
      - entity: person.t
    theme_mode: light
    hours_to_show: 4
    default_zoom: 17
```

**Informations (please complete the following information):**  
 - OS: Tried on Mac and iPhone
 - Browser/App: Chrome, Safari and HA App
 - Bubble Card version: 2.4.0
 - Home Assistant version: 2025.3.3

**Comment by enedberg** [comment]
Bug is still present with Home Assistant Core 2025.4.2.
I have not tried the beta of Bubble Card

**Comment by Clooos** [comment]
Hi! I tried and the only way to fix this issue is to turn on the background update of that pop-up, this is the setting bellow:

<img width="479" alt="Image" src="https://github.com/user-attachments/assets/655bfa35-0b2c-4d46-8b63-18d8cba81b60" />

I recommend to not add too many cards in that pop-up, as this feature just hide the pop-up, its content is not removed from the dashboard when closed.

**Comment by Clooos** [comment]
I found the issue! And like I said the "background update" is needed for this case, but there is an issue in the current builds that doesn't make this mode working as expected.

This will be fixed in the next beta, I'm planning to release it in a few days 🙂

**Comment by enedberg** [comment]
Thanks a lot for checking and confirming! I'll see if I update to the beta or if I wait for the stable release.

**Comment by Clooos** [comment]
Hi again, this issue was fixed in the latest beta, don't hesitate to try it, this version is really stable 🙂

**Comment by Clooos** [comment]
One more thing, this fix seems to only works if the map card is at the top of the pop-up, I really don't know why.

I can't wait for your feedback! 😄

**Comment by enedberg** [comment]
I am sad to say that the fix does not work every time. It looks to be better than before, but not stable.

It seems to work, but if I refresh the page or navigate to another dashboard and back it still shows the wrong zoom level. 

I have made sure the pop-up is the last card on the dashboard and that the map is the first card (after pop-up) in the vertical-stack.

**Comment by Clooos** [comment]
And you have toggled the "background update" feature?

**Comment by enedberg** [comment]
Yes, that setting is on

**Comment by Clooos** [comment]
Damn 😅 On my test it was working perfectly after my fix. I will check again, and I really hope I will find a better way.

**Comment by Clooos** [comment]
I can reproduce your issue, and indeed when moving to another view then coming back the zoom is wrong again... and I really don't know why 😅

This might be a real incompatibility, you can try to report it on the [Home Assistant GitHub](https://github.com/home-assistant/frontend/issues), but I have a doubt they will fix something related to a custom card. The best way would be to find a way to reproduce this without Bubble Card.

**Comment by Clooos** [comment]
Or just keep everything in one view, that's how my dashboard is built 🙂
