### ISSUE TITLE
Media player card - missing buttons

### ISSUE THREAD

**Issue by BooBoss** [Clooos/Bubble-Card#1930]
For any feature request you can open a new discussion here:  
https://github.com/Clooos/Bubble-Card/discussions/categories/feature-requests

For any question you can open a new discussion here:  
https://github.com/Clooos/Bubble-Card/discussions/categories/q-a

**Describe the bug**  

I was editing one of the Media Player bubble cards and out of sudden most of control buttons disappeared. I tried to create new media player card, select different media player, create card in different dashboard - nothing helps. While in editing mode card looks like this:

<img width="622" height="163" alt="Image" src="https://github.com/user-attachments/assets/bab65ebf-aa34-4c7c-b404-72a82a38e5cc" />

But once I exit edit mode card looks like this:

<img width="628" height="80" alt="Image" src="https://github.com/user-attachments/assets/57639eda-44fb-48a3-a87e-0a60797e3067" />

HA restart doesn't help. Of course media players being tested were online and controllable. To prove that I created default media player card for same players, example:

<img width="615" height="172" alt="Image" src="https://github.com/user-attachments/assets/c0896b6b-1fb0-4f68-b047-c2821a798714" />

**Information (please complete the following information):**  
 - OS: Web browser, Android companion app
 - Browser/App: every browser
 - Bubble Card version: 3.0.4
 - Home Assistant version: 2025.11.3

Thank you! 🍻

**Comment by Clooos** [comment]
Hi! I've made some changes in v3.1.0-beta.1, could you try it to see if it still happens? (I'm unable to reproduce this)

https://github.com/Clooos/Bubble-Card/releases/tag/v3.1.0-beta.1

**Comment by BooBoss** [comment]
Unfortunatelly new version didn't solved the issue.

**Comment by Jonsonmon** [comment]
Same issue here. It's something with the Companion app. In browser it's not happens

**Comment by Clooos** [comment]
Is the cache correctly cleared for the Companion app?

**Comment by Jonsonmon** [comment]
> Is the cache correctly cleared for the Companion app?

Actually yes, I tried to clear cache thousand times. Even cleared WebView cache. Nothing helps

**Comment by Clooos** [comment]
Ok good to know, I will try in mobile view to see what's wrong here 👌

**Comment by BooBoss** [comment]
For me it happens both in browser and companion app.

**Comment by Clooos** [comment]
This should be fixed in v3.1.0-beta.5 (available today or tomorrow), but since I can't reproduce this I can't be sure 🤞

**Comment by borez** [comment]
Just updated to 3.1.0 beta 5, seeing the same issue.

**Comment by BooBoss** [comment]
Seems like @borez and I have two different root causes of the problem because for me new version solved the problem, so thank you :-) I'm wondering what @Jonsonmon has to say because for him it happened only in companion app while for me everywhere.

**Comment by Jonsonmon** [comment]
@BooBoss @Clooos 
I had two issues that started at the same time. One was with the media player and the other was with this switch button that I will show in the video. Both started at the same time.
I no longer have the media player on the dashboard, so I have no way to check it.
But the switch button is still there and the problem remains.
Notice how in edit mode it's normal, and the moment you exit edit mode it goes back to blue.
There is no visibility condition on the button.
Pay attention to the "Beep" button.

https://github.com/user-attachments/assets/bad890aa-19ae-44f2-ac6f-798a7df0e273

**Comment by BooBoss** [comment]
@Jonsonmon I see that in edit mode it seems to be disabled but in normal mode enabled. But in edit mode quite often buttons don't show their real state. Question is if in normal mode it shows what it's suppose to show.

**Comment by Jonsonmon** [comment]
> [@Jonsonmon](https://github.com/Jonsonmon) I see that in edit mode it seems to be disabled but in normal mode enabled. But in edit mode quite often buttons don't show their real state. Question is if in normal mode it shows what it's suppose to show.

In normal mode it shows me the button with a blue background, the icon stays fine, and the button is not pressed at all.
Look at the video at the beginning. It's blue

**Comment by borez** [comment]
3.1.0-beta.6 has solved the problem for me! Thank you!
