### ISSUE TITLE
Refresh everytime

### ISSUE THREAD

**Issue by Dave811** [Clooos/Bubble-Card#207]
Hi I have a problem, everytime when I open the dashboard with the bubble popup it seems the page reloads.
I installed it through HACS and also enabled the pop up optimization.
Does anyone know what is happening on my side?

https://github.com/Clooos/Bubble-Card/assets/21054638/030246c9-d4c7-41e3-b129-986eb87acf25

**Comment by ayostepht** [comment]
This is also happening to me and is unfortunately making bubble card unusable :( . FWIW I have HA installed on Docker, in case that is helpful at all.

**Comment by Clooos** [comment]
Hi and thanks for your feedback, did you had the `module_installed: true` in one Bubble Card? If yes try to remove it. I also had that issue once.

**Comment by Clooos** [comment]
This is fixed in v1.5.2! 😃
https://github.com/Clooos/Bubble-Card/releases/tag/v1.5.2

**Comment by ayostepht** [comment]
Thank you! Just checked pre-update and you are right it was only when it
had that snippet in the card! Will upgrade soon and confirm it is fixed.
Really appreciate your help and work on this project, it’s incredible!!

**Comment by Dave811** [comment]
I updated to the newest release and deleted the extra module from the configuration.yml But the popup refreshs everytime again. Perhabs I did something wrong.
This is my code from the Dashboard. The Video is not new but it looks the same.
```views:
  - title: Home
    cards:
      - type: vertical-stack
        cards:
          - type: custom:bubble-card
            hash: '#pop-up-wohnzimmer'
            name: Wohnzimmer
            icon: mdi:sofa
            back_open: true
            card_type: pop-up
          - type: custom:better-thermostat-ui-card
            entity: climate.better_thermostat_wohnzimmer
            disable_window: true
            disable_summer: true
          - type: custom:scheduler-card
            include:
              - climate.better_thermostat_wohnzimmer
            exclude: []
            discover_existing: false
      - type: vertical-stack
        cards:
          - type: custom:bubble-card
            hash: '#pop-up-esszimmer'
            name: Esszimmer
            icon: mdi:food
            back_open: true
            card_type: pop-up
          - type: custom:better-thermostat-ui-card
            entity: climate.better_thermostat_esszimmer
            disable_window: true
            disable_summer: true
          - type: custom:scheduler-card
            include:
              - climate.better_thermostat_esszimmer
            exclude: []
      - type: vertical-stack
        cards:
          - type: custom:bubble-card
            hash: '#pop-up-simon'
            name: Simon
            icon: mdi:bed
            back_open: true
            card_type: pop-up
          - type: custom:better-thermostat-ui-card
            entity: climate.better_thermostat_simon
            disable_window: true
            disable_summer: true
          - type: custom:scheduler-card
            include:
              - climate.better_thermostat_simon
            exclude: []
            discover_existing: false
      - type: vertical-stack
        cards:
          - type: custom:bubble-card
            hash: '#pop-up-badezimmer'
            name: Badezimmer
            icon: mdi:toilet
            back_open: true
            card_type: pop-up
          - type: custom:better-thermostat-ui-card
            entity: climate.better_thermostat_badezimmer
            disable_window: true
            disable_summer: true
          - type: custom:scheduler-card
            include:
              - climate.better_thermostat_badezimmer
            exclude: []
            discover_existing: false
      - type: horizontal-stack
        cards:
          - show_name: true
            show_icon: true
            type: button
            tap_action:
              action: navigate
              navigation_path: '#pop-up-wohnzimmer'
            name: Wohnzimmer
            icon: mdi:sofa
          - show_name: true
            show_icon: true
            type: button
            tap_action:
              action: navigate
              navigation_path: '#pop-up-esszimmer'
            name: Esszimmer
            icon: mdi:food
          - show_name: true
            show_icon: true
            type: button
            tap_action:
              action: navigate
              navigation_path: '#pop-up-badezimmer'
            name: Badezimmer
            icon: mdi:toilet
          - show_name: true
            show_icon: true
            type: button
            tap_action:
              action: navigate
              navigation_path: '#pop-up-badezimmer'
            name: Simon
            icon: mdi:bed
```

**Comment by Clooos** [comment]
If you still have this issue it's probably because your cache isn't cleared correctly and that you are still on the previous release. This new version don't refresh anything anymore.

**Comment by Dave811** [comment]
I checked again. 
- I am on the newest version
- I deleted the extra module
- I changed the bubble-pop-up to bubble-card
- I also cleaned my browser cache and used another browser that never opened homeassistant before
But if I switch dashboards, the cards are flying like in the video

**Comment by Dave811** [comment]
So I tried it, and it says in the editor `Pop-up 👍 Optimized mode `
But its still happening:

This is my config now:
```views:
  - title: Home
    cards:
      - type: vertical-stack
        cards:
          - type: custom:bubble-pop-up
            hash: '#pop-up-wohnzimmer'
            name: Wohnzimmer
            icon: mdi:sofa
          - type: custom:better-thermostat-ui-card
            entity: climate.better_thermostat_wohnzimmer
            disable_window: true
            disable_summer: true
          - type: custom:scheduler-card
            include:
              - climate.better_thermostat_wohnzimmer
            exclude: []
            discover_existing: false
      - type: vertical-stack
        cards:
          - type: custom:bubble-pop-up
            hash: '#pop-up-esszimmer'
            name: Esszimmer
            icon: mdi:food
          - type: custom:better-thermostat-ui-card
            entity: climate.better_thermostat_esszimmer
            disable_window: true
            disable_summer: true
          - type: custom:scheduler-card
            include:
              - climate.better_thermostat_esszimmer
            exclude: []
      - type: vertical-stack
        cards:
          - type: custom:bubble-pop-up
            hash: '#pop-up-simon'
            name: Simon
            icon: mdi:bed
          - type: custom:better-thermostat-ui-card
            entity: climate.better_thermostat_simon
            disable_window: true
            disable_summer: true
          - type: custom:scheduler-card
            include:
              - climate.better_thermostat_simon
            exclude: []
            discover_existing: false
      - type: vertical-stack
        cards:
          - type: custom:bubble-pop-up
            hash: '#pop-up-badezimmer'
            name: Badezimmer
            icon: mdi:toilet
          - type: custom:better-thermostat-ui-card
            entity: climate.better_thermostat_badezimmer
            disable_window: true
            disable_summer: true
          - type: custom:scheduler-card
            include:
              - climate.better_thermostat_badezimmer
            exclude: []
            discover_existing: false
      - type: horizontal-stack
        cards:
          - show_name: true
            show_icon: true
            type: button
            tap_action:
              action: navigate
              navigation_path: '#pop-up-wohnzimmer'
            name: Wohnzimmer
            icon: mdi:sofa
          - show_name: true
            show_icon: true
            type: button
            tap_action:
              action: navigate
              navigation_path: '#pop-up-esszimmer'
            name: Esszimmer
            icon: mdi:food
          - show_name: true
            show_icon: true
            type: button
            tap_action:
              action: navigate
              navigation_path: '#pop-up-badezimmer'
            name: Badezimmer
            icon: mdi:toilet
          - show_name: true
            show_icon: true
            type: button
            tap_action:
              action: navigate
              navigation_path: '#pop-up-badezimmer'
            name: Simon
            icon: mdi:bed
```
