### ISSUE TITLE
Popup button randomly stops working

### ISSUE THREAD

**Issue by TheNewKind** [Clooos/Bubble-Card#258]
Popup button randomly stops opening, URL states it's being called but the card is not opening when the button in the horizontal bar is being pressed.
![image_2023-12-23_220701995](https://github.com/Clooos/Bubble-Card/assets/152030104/8f1b9520-c6aa-4355-a664-d6e23317c021)

**Comment by Clooos** [comment]
I also had this issue but it should be fixed in v1.6.3.

**Comment by TheNewKind** [comment]
> I also had this issue but it should be fixed in v1.6.3.

Oh alright, is there any solution to get it to work again in the meantime until that version is released?

**Comment by Clooos** [comment]
Bien sûr, voici votre texte corrigé en anglais :

Could you try this early version by installing it with the [Without HACS](https://github.com/Clooos/Bubble-Card?tab=readme-ov-file#without-hacs) installation method? This is the version that I'm currently using on my personal setup and I haven't had this issue since. I hope that it wasn't just luck.

[Bubble Card v1.6.0-beta.3 test.zip](https://github.com/Clooos/Bubble-Card/files/13760366/Bubble.Card.v1.6.0-beta.3.test.zip)

**Comment by 2rememberyou** [comment]
Same issue here. Where do I place those files for testing. Would like to try this as well.

**Comment by TheNewKind** [comment]
I tried installing the beta 3 without HACS which didn't work. Then tried installing several older versions through HACS which didn't work either. One button is still not opening it's card when it's being called for.

**Comment by 2rememberyou** [comment]
A restart did it for me. Full restart of the tablet.

**Comment by 2rememberyou** [comment]
With that being said, something is definitely wrong with the edit feature.
When you press edit it's a whole garbled mess cards are all jumbled
together. For me anyways.

**Comment by TheNewKind** [comment]
So what ended up working for me was changing the hash and hash link to something else. I don't know how to replicate the bug precisely but it seemed to bug out for me twice now after tapping the button in quick succession. Glad i found a temporary fix though! Thanks for all the work and effort building and maintaining Bubble Card @Clooos!

**Comment by Clooos** [comment]
> With that being said, something is definitely wrong with the edit feature. When you press edit it's a whole garbled mess cards are all jumbled together. For me anyways.

Indeed I can confirm that, I have this issue too on v1.6.0-beta.3 test, I should have messed up with something because it was not the case before.

**Comment by Clooos** [comment]
> So what ended up working for me was changing the hash and hash link to something else. I don't know how to replicate the bug precisely but it seemed to bug out for me twice now after tapping the button in quick succession. Glad i found a temporary fix though! Thanks for all the work and effort building and maintaining Bubble Card @Clooos!

I'm still not sure to understand correctly your issue, this is weird that changing the hash fixed it.

**Comment by Clooos** [comment]
> With that being said, something is definitely wrong with the edit feature. When you press edit it's a whole garbled mess cards are all jumbled together. For me anyways.

This is fixed in the last beta!
https://github.com/Clooos/Bubble-Card/releases/tag/v1.6.0-beta-3

**Comment by 2rememberyou** [comment]
Thank you sir.  You are the best!
