### ISSUE TITLE
Horizontal Stack Crowding

### ISSUE THREAD

**Issue by peterxrock** [Clooos/Bubble-Card#359]
Everything was fine on 1.5.3. Updated to 1.6.4 and the horizontal cards now condense and are unusable. Running HA 2024.1.3.

<img width="251" alt="Screenshot 2024-01-12 at 12 43 59 PM" src="https://github.com/Clooos/Bubble-Card/assets/69395225/091e03f2-7a27-4b50-9d0e-49925ecc09ce">

<img width="561" alt="Screenshot 2024-01-13 at 12 12 40 PM" src="https://github.com/Clooos/Bubble-Card/assets/69395225/f4749b7b-62be-4e4b-a0a3-9ab568d30f52">

Not sure if this is related:

Logger: frontend.js.latest.202401040
Source: components/system_log/__init__.py:300
First occurred: 12:06:54 PM (1 occurrences)
Last logged: 12:06:54 PM

Uncaught error from Safari 17.1 on Mac OS 10.15.7 TypeError: undefined is not an object (evaluating 'hass.states[entityId].attributes') hass (/hacsfiles/Bubble-Card/bubble-card.js:1:2050) createCardElement (src/panels/lovelace/cards/hui-stack-card.ts:104:14) createCardElement (src/panels/lovelace/cards/hui-stack-card.ts:121:46) createCardElement (src/panels/lovelace/cards/hui-stack-card.ts:110:26) dispatchEvent ([native code]::) event (src/common/dom/fire_event.ts:76:21) tag.includes (src/panels/lovelace/create-element/create-element-base.ts:127:14)

**Comment by peterxrock** [comment]
Okay, this was caused by one of the entities I use to display the light status being unavailable (but it shouldn't do this).

**Comment by peterxrock** [comment]
Updated to 1.7.0 and there's still something off... 
<img width="544" alt="Screenshot 2024-02-19 at 12 29 37 AM" src="https://github.com/Clooos/Bubble-Card/assets/69395225/3a738cfb-a2a0-4f27-98bd-f26caa569418">

**Comment by Clooos** [comment]
> Updated to 1.7.0 and there's still something off... <img alt="Screenshot 2024-02-19 at 12 29 37 AM" width="544" src="https://private-user-images.githubusercontent.com/69395225/305823687-3a738cfb-a2a0-4f27-98bd-f26caa569418.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgzNDA5NzcsIm5iZiI6MTcwODM0MDY3NywicGF0aCI6Ii82OTM5NTIyNS8zMDU4MjM2ODctM2E3MzhjZmItYTJhMC00ZjI3LTk4YmQtZjI2Y2FhNTY5NDE4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE5VDExMDQzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE0ZTk0ZGI2NTc2N2IyYjI2MDU4YWU0NjZmNDNmNTJmZDBhYjEwMTE1ODE3ZTc1ODRiMmQ0NjljMWQ3ZjM5ZjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fnn9xzZy1gGXANU-3BPt-n4W_RtRKwUnOAwSJrweQeI">

You can open the editor then wait a bit, this should be fixed this way 🙂

**Comment by peterxrock** [comment]
> > Updated to 1.7.0 and there's still something off... <img alt="Screenshot 2024-02-19 at 12 29 37 AM" width="544" src="https://private-user-images.githubusercontent.com/69395225/305823687-3a738cfb-a2a0-4f27-98bd-f26caa569418.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgzNDA5NzcsIm5iZiI6MTcwODM0MDY3NywicGF0aCI6Ii82OTM5NTIyNS8zMDU4MjM2ODctM2E3MzhjZmItYTJhMC00ZjI3LTk4YmQtZjI2Y2FhNTY5NDE4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE5VDExMDQzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE0ZTk0ZGI2NTc2N2IyYjI2MDU4YWU0NjZmNDNmNTJmZDBhYjEwMTE1ODE3ZTc1ODRiMmQ0NjljMWQ3ZjM5ZjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fnn9xzZy1gGXANU-3BPt-n4W_RtRKwUnOAwSJrweQeI">
> 
> 
> 
> You can open the editor then wait a bit, this should be fixed this way 🙂 

Same issue. The font seems larger now but the spacing is still off. I don't have any customization - just out of the box settings. ![image](https://github.com/Clooos/Bubble-Card/assets/69395225/25cb3587-ccc3-4537-bd94-5cd5eab82cf4)

**Comment by Clooos** [comment]
Have you tried opening the editor or clearing your cache? These are the two solutions to reset the horizontal buttons stack positioning.

**Comment by peterxrock** [comment]
Thanks! Clearing the cache fixed it. However, the original issue still stands. Instead of the original crowding issue, if an entity in the card is unavailable, it errors out. (This is when the kitchen occupancy sensor goes offline, which it does occasionally).
<img width="509" alt="Screenshot 2024-02-19 at 11 04 21 PM" src="https://github.com/Clooos/Bubble-Card/assets/69395225/d5793071-12e4-4eb3-9c1b-d008f7d4b7ba">

**Comment by Clooos** [comment]
I will take a closer look at that.

**Comment by peterxrock** [comment]
I’m still having the crowding issue on mobile, too. I can try uninstalling and reinstalling, but maybe there's an easier way to clear the cache on the app?

**Comment by Clooos** [comment]
I was unable to replicate this issue, I've added an unavailable entity but I had no issues. I'm clueless right now but opening the HBS editor on your device should clear the HBS cache.

**Comment by peterxrock** [comment]
That fixed the cache issue. I figured out the entity was being disabled (when the integration was reloading) and not unavailable, so that explains that. Thanks for the help!
