### ISSUE TITLE
bubble popup card very laggy on android/ not opening on first click

### ISSUE THREAD

**Issue by liamwibo** [Clooos/Bubble-Card#661]
I added the bubble card to my dashboard and it worked super well on my pc no lag no stutter always opening on first click but on my android phone it,s very laggy/stuttery and sometimes when i fully close the app and reopen it i have click a few times/refresh the dashboard to get the bubble popup card to open 

**To Reproduce**  
1. install bubble card trought HACS
2. add a popup card in a dashboard (default settings)
3. open the popup card on an android phone (not tested on an iphone)

**Expected behavior**  
the popup card has a smooth animation and comes up on the first click

**YAML**  

```yaml
views:
  - title: "Home"
    path: 0
    icon: "mdi:flower"
    cards:
      - type: "vertical-stack"
        cards:
          - type: "custom:bubble-card"
            card_type: "pop-up"
            hash: "#weather"
            margin_top_mobile: -56px
            name: Kitchen
            icon: mdi:fridge
          - type: custom:hourly-weather
            entity: weather.forecast_home
            num_segments: 14 # optional, defaults to 12
            name: Volgende 12 uur # optional, defaults to "Hourly Weather"
          - type: custom:button-card
            template: custom_card_httpedo13_sun
            variables:
              language: "nl"
```

**Informations:**  
 - android
 - app
 - Bubble Card version: 2.1.0
 - Home Assistant version: 2024.7.2

**Comment by Clooos** [comment]
Hi! Have you tried to clear your Android app cache?

**Comment by liamwibo** [comment]
yea cleared it and also all date but still laggy

**Comment by Clooos** [comment]
Can you try with `hide_backdrop: true` on your pop-up?

**Comment by bambucha3** [comment]
Same issue here.
Just tried `hide_backdrop: true`, but it still lags.
The popup show animation lags a lot, even on my S22 Ultra.

**Comment by Clooos** [comment]
Any error in your browser console? I don't have that issue on Android, even on an old iPad from 2018.

There is also the possibility that there is a card in one of the pop-up that make it lag. Have you tried to identify what card is making it lag?

**Comment by bambucha3** [comment]
I have 3 NSPanel PROs as displays running android 8.1.
And also my phone. All using the home assistant app.
I have very basic setup on home screen - 6 switches and inside the popup 4 switches for lights and a header. Its all bubble-card.
There are no errors in the console.

Dont get me wrong, its a lot better with `hide_backdrop: true` but still lags.

**Comment by Clooos** [comment]
Thank you for the details, I will take a look if there is something that I can optimize more. 

It's also possible that the blur effect combined with the animation can slow down the opening on some setups, can you try to add this custom style to your pop-up cards?

```yaml
.bubble-pop-up {
  filter: none !important;
  opacity: 1 !important;
}
```

**Comment by bambucha3** [comment]
I dont know what `filter:` is supposed to do, but it didn't seem to change anything on any device.
I removed the blur effect (background is hidden, and blur is set to 0). Or maybe something stays on?
Its definitely the animation though, I tried today to use the swipe home assistant plugin, and they have a swipe animation, which played smoothly on all my devices. But it had other issues :)

**Comment by Flizzledoo** [comment]
I was having the same issue on my Samsung phone. I tried redownloading an older version in HACS, and it was immediately fixed. But then I upgraded again to the latest version to try to reproduce the issue, and it just stayed fixed even on the latest. So maybe try redownloading it? Hope that helps

**Comment by Clooos** [comment]
Thank you for the feedback @Flizzledoo, this looks like a cache issue, it is cleared when you change/update the version, but it only clear the cache on the device that starts the update.

So to fix this issue you can just clear the HA companion app cache, no need to downgrade.

**Comment by bambucha3** [comment]
I tried clearing the cache on my phone and the NSpanels, its better, but still not smooth :)
I dont have much experience with web stuff, but i checked the profiler a bit, and saw a high jump in cpu usage when you click the button to open the popup. Its especially noticable on the NSpanels since they have shitty cpus.
Probably the creation of the popup lags the animation, since it takes more than 1 frame. 
Is there a way to wait until its fully loaded and then play the animation?

**Comment by Clooos** [comment]
This is something that I need to try, it is indeed possible that there is to much code that is executed at the same time when a pop-up is opening.

But I still don't understand why clearing the cache helps. I have some issues that I really need to fix first then I will definitely take a look at that.

**Comment by liamwibo** [comment]
sorry i didn't see your messages but i like to add that the stuttering is not consistent. It's good now but 2 days ago it was lagging

**Comment by liamwibo** [comment]
I have just installed homeassistant os on another machine and only installed hacs + bubble card didn't configure any addons except ssh no integrations except hacs and the bubble card is still laggy so i don't think it's a compatibility problem of some sort with other custom cards or homeassistant cards.

**Comment by Clooos** [comment]
I've just released a new version that optimize the pop-ups a lot 🤞

https://github.com/Clooos/Bubble-Card/releases/tag/v2.2.0-beta.1

**Comment by liamwibo** [comment]
hi just wanted to say thx for the update and putting in the time to fix the laggy animations they have improved a lot since the last update. The animation is now much better but the first 1 or 2 popup i open are still laggy but after that it's butter smooth. Also i think this is a app problem because i have not encoutered this yet in the browser but sometimes when switching between popups fast and you open a new popup shortly after closing another the background blurs like it does when the popup opens but the popup itself doesn't appear. but these are overall minor issues and the bubble cards are so much more usable now. Thx for the update.

![image0](https://github.com/user-attachments/assets/5056c24d-73b1-4513-b71d-a2fae836d891)

Here is a screenshot of what it looks like when the popup doesn't open i think this is because the popup that was open didn't have enough time to close and was still in the closing annimation and caused this weird behaviour.

**Comment by Clooos** [comment]
This issue is now fixed as well in the new beta!

https://github.com/Clooos/Bubble-Card/releases/tag/v2.2.0-beta.2

**Comment by Maaaaarc** [comment]
Hi, thanks for your effort. In my case, the animation is still a bit laggy, but it's much better without the backdrop. 

I'm okay with using it without the backdrop, but I was wondering if there's a way to disable the backdrop while still preventing another card from being triggered (which is outside of the popup). Is that possible?


So that I can just click beside the popup to close it, I don't want another button to be pressed.

**Comment by Clooos** [comment]
If you want you can set the backdrop blur to 0 and kipping it, tell me if it helps!

**Comment by Maaaaarc** [comment]
Thanks for the quick response!

This is my configuration, but I’m still experiencing the blur effect. Am I missing something?
![image](https://github.com/user-attachments/assets/8f3c1ba4-c195-4986-8f40-8d965cfe671a)



```
type: vertical-stack
cards:
  - type: custom:bubble-card
    card_type: pop-up
    hash: '#garden'
    name: Garden
    icon: mdi:shovel
    entity: 
    show_header: true
    force_icon: false
    show_state: false
    show_last_changed: false
    sub_button: []
    card_layout: normal
    hide_backdrop: false
    bg_color: '#32a852'
    bg_blur: 0
    ....
```

Additional Information:
I’m using a Samsung Tab A8 with Fully Kiosk Browser. After restarting the device, it improved significantly and was much smoother, but after a few minutes, it became laggy again.

**Comment by Clooos** [comment]
Have you tried to refresh after setting it to 0?

**Comment by Maaaaarc** [comment]
Yes, on multiple Devices.

**Comment by Clooos** [comment]
I will check that.

**Comment by bambucha3** [comment]
Just wanted to say, that the beta 3 works a lot better on my NSPanels.
It is like 5x smoother 👍 
Great work!

**Comment by liamwibo** [comment]
Hi Beta 3 fixes the issue for me where the pop ups don't appear correctly but it makes it stutter again. I have tried clearing my cache

**Comment by Clooos** [comment]
Have you also tried to reboot your device?

**Comment by liamwibo** [comment]
yea but it seems to be switching between beta 1 or 2 idk wich one with the glitch that was patched in beta 3 regarding popups not showing when opening one to quick after closing another one and beta 3 maybe i haven't updated it the right way? What way do you recommend updating since updating with hacs to a specific version is deprecated?

**Comment by Clooos** [comment]
I've just released the new stable version, the pop-ups are now even faster that in the previous beta.

@liamwibo your issue is also fixed as well!

https://github.com/Clooos/Bubble-Card/releases/tag/v2.2.0

**Comment by bambucha3** [comment]
Can confirm, magical.

**Comment by liamwibo** [comment]
Thank you so much can confirm all the issues i had now are fixed popup are butter smooth no weird behavior when opening popups fast and sorry for the troubles.
