### ISSUE TITLE
v2.2.0-beta.1 Pop-up background blur sometimes persists after closing popup

### ISSUE THREAD

**Issue by CZonin** [Clooos/Bubble-Card#693]
**Describe the bug**  
After opening and then closing a pop-up, the background blur will sometimes persist and can only be fixed by refreshing the tab/restarting app.

**Expected behavior**  
Background blur will always be dismissed when pop-up is dismissed.

**Screenshots**  
![Screenshot_20240809-114040](https://github.com/user-attachments/assets/4bf3e2ef-277b-439b-92fd-6b6ad321edc4)

**YAML**  
Here's YAML from one of my pop-ups if it helps:

```
type: vertical-stack
cards:
  - type: custom:bubble-card
    card_type: pop-up
    hash: '#living-room'
    sub_button:
      - entity: sensor.living_room_thermostat_temperature
        show_background: false
        show_state: true
      - entity: sensor.living_room_thermostat_humidity
        show_background: false
        show_state: true
    card_layout: normal
    show_header: true
    name: Living Room
    show_icon: false
    scrolling_effect: false
    show_name: false
    styles: |2-
        .bubble-button-card-container {
          background: none !important;
        }
    icon: ''
    tap_action:
      action: none
    double_tap_action:
      action: none
    hold_action:
      action: none
    button_action:
      tap_action:
        action: none
      double_tap_action:
        action: none
      hold_action:
        action: none
    margin_top_mobile: calc(100vh - 325px)
    margin_top_desktop: calc(100vh - 325px)
    shadow_opacity: '0'
    bg_blur: '14'
    bg_opacity: '100'
    hide_backdrop: false
  - type: custom:bubble-card
    card_type: button
    button_type: slider
    entity: light.living_room_light
    name: Light
    card_layout: large
    tap_action:
      action: toggle
    double_tap_action:
      action: none
    hold_action:
      action: more-info
  - type: custom:bubble-card
    card_type: separator
  - type: custom:bubble-card
    card_type: media-player
    entity: media_player.living_room_shield
    name: Shield
    icon: mdi:television
    tap_action:
      action: toggle
    double_tap_action:
      action: none
    hold_action:
      action: more-info
    button_action:
      double_tap_action:
        action: none
      hold_action:
        action: more-info
    show_state: true
    card_layout: large

```

**Informations (please complete the following information):**  
 - OS: Windows 11/Android
 - Browser/App: Chrome/Official App
 - Bubble Card version: v2.2.0-beta.1
 - Home Assistant version: 2024.7.4

**Comment by Clooos** [comment]
Thank you for the feedback!

**Comment by pgale** [comment]
Same on my devices - Android TSV's and iPhone 15 pro. When closing  pop up, the underlying page never shows again.

**Comment by Batzi1967** [comment]
Same on my device - Android with offiziell app. When closing pop up, the underlying page never shows again. I must restart the app

**Comment by fellipute** [comment]
Same here, on desktop and mobile.

**Comment by regnighc** [comment]
Same for me also, app and browser

**Comment by tigers75** [comment]
Same for me here, but not sometimes. Samsung S23ultra and android official app. Haven't tested on desktop yet.

**Comment by Clooos** [comment]
This is now fixed!

https://github.com/Clooos/Bubble-Card/releases/tag/v2.2.0-beta.2

**Comment by pgale** [comment]
Thanks Clooos :) working ok here too on my devices. Having problems trying to clear and update the cache on the iOS companion app - but that's an HA thing. Cache seems to always be a problem.

**Comment by Clooos** [comment]
On the iOS app you can go to your HA settings, then on Companion App > Debug > Clear frontend cache.

**Comment by pgale** [comment]
Yes I did that but it was still showing the previous version. I came back to it 10m or so later and tried again and it was then picking up the new version. Odd.

**Comment by Clooos** [comment]
Odd indeed, the HA cache can be really treaky 😅

Glad that it's fixed!

**Comment by CZonin** [comment]
Fixed, thanks for the update @Clooos !

**Comment by CZonin** [comment]
@Clooos this is happening again on 2.2.1. Seems to be somewhat rare though. It wasn't happening at all after it was fixed in 2.2.0-beta2.
