### ISSUE TITLE
Climate card bug with Bosch BTH-RM230Z

### ISSUE THREAD

**Issue by klatka** [Clooos/Bubble-Card#877]
I have some Bosch [BTH-RM230Z](https://www.zigbee2mqtt.io/devices/BTH-RM230Z.html#bosch-bth-rm230z) connected via Zigbee2Mqtt. Unfortunately, I cannot use them with the climate card because they don't provide the attribute `temperature`. 

```yaml
hvac_modes: off, heat, cool
min_temp: 4.5
max_temp: 30
target_temp_step: 0.5
current_temperature: 21.7
target_temp_high: 30
target_temp_low: 20
hvac_action: idle
friendly_name: Bodenheizung Wohnbereich
supported_features: 386
```

Best config I can do is:
```yaml
type: custom:bubble-card
card_type: climate
entity: climate.bosch_room_thermostat_ii_1
sub_button:
  - name: HVAC modes menu
    select_attribute: hvac_modes
    show_arrow: false
  - name: Climate temperature
    show_attribute: true
    attribute: target_temp_low
    icon: mdi:thermometer
    state_background: false
show_last_changed: false
show_state: false
show_attribute: true
attribute: hvac_action
```

But I cannot make the + and - sub buttons work.

**Comment by Clooos** [comment]
Hi and thank you for the feedback! So in your case these buttons should control the target_temp_low attribute?

**Comment by klatka** [comment]
> Hi and thank you for the feedback! So in your case these buttons should control the target_temp_low attribute?

Yes but only if the state is `heat`. As you can see in the picture below this thermostat also supports cooling. So in the state `cool` the buttons should control the `target_temp_high` attribute.

<img width="580" alt="image" src="https://github.com/user-attachments/assets/1d824389-6143-40b3-a699-c127ae13e086">

The [docs](https://www.home-assistant.io/integrations/climate/#action-climateset_temperature) mentions also the attribute `hvac_mode`. Perhaps the controlled attribute should be set based on this.

**Comment by Clooos** [comment]
Thank you for the details, now I just wonder how I will handle that case. Maybe with both temperature values in two sub-buttons? And like you said, the buttons should control the corresponding attribute based on the `hvac_mode`.

What do you think?

**Comment by Clooos** [comment]
Hi! I released a new beta that should supports your thermostat, just remove your previous card then add a new one 🤞

https://github.com/Clooos/Bubble-Card/releases/tag/v2.3.0-beta.4

**Comment by cromelex** [comment]
> Hi! I released a new beta that should supports your thermostat, just remove your previous card then add a new one 🤞
> 
> https://github.com/Clooos/Bubble-Card/releases/tag/v2.3.0-beta.4

Hi @Clooos, I have the same thermostat and I have just tried the latest beta. Your climate card is solving me issues in that it hides the "high temp" which is unnecessary in "heat" mode and only creates clutter. 
I actually only tried this because I saw the changelog about the Bosch Thermostat. This is with the latest beta.

![image](https://github.com/user-attachments/assets/31d59f2f-e525-44e5-96bc-9ae483ddd67f)

The +/- signs at the moment are still trying to change the "temperature" parameter, so I get the following error on press.
![image](https://github.com/user-attachments/assets/02c8c38e-7763-4bd7-8d61-b5291ea0db06)

**Comment by klatka** [comment]
I tried the new beta, thank you for the fast release.

Like cromelex, I also think that there is too much clutter and the icons need to be switched. The thermostat should heat up to 20 degrees Celsius and cool down from 30 degrees Celsius:
![image](https://github.com/user-attachments/assets/3d452197-52de-4a08-8a14-39d92620fdd2)
+/- sub buttons still doesn't work as cromelex already mentioned.

> Thank you for the details, now I just wonder how I will handle that case. Maybe with both temperature values in two sub-buttons? And like you said, the buttons should control the corresponding attribute based on the `hvac_mode`.
> 
> What do you think?

To reduce clutter maybe only one temperature should be displayed corresponding to the current `hvac_mode`.
In addition if mode is `heat` then +/- buttons should control `target_temp_high` and for mode `cool` the controlled attribute should be `target_temp_low`.

**Comment by cromelex** [comment]
> To reduce clutter maybe only one temperature should be displayed corresponding to the current `hvac_mode`.
> In addition if mode is `heat` then +/- buttons should control `target_temp_high` and for mode `cool` the controlled attribute should be `target_temp_low`.

It's the other way around. In `heat` you want it to set `target_temp_low` (ie, the *minimum* temperature, that you want to be reached by heating). And `cool` sets `target_temp_high`.

**Comment by klatka** [comment]
> > To reduce clutter maybe only one temperature should be displayed corresponding to the current `hvac_mode`.
> > In addition if mode is `heat` then +/- buttons should control `target_temp_high` and for mode `cool` the controlled attribute should be `target_temp_low`.
> 
> It's the other way around. In `heat` you want it to set `target_temp_low` (ie, the _minimum_ temperature, that you want to be reached by heating). And `cool` sets `target_temp_high`.

You are right

**Comment by Clooos** [comment]
Thank you all for the feedbacks! I will keep all you said in mind for the next release 👌

**Comment by SLaks** [comment]
Thermostats with auto-changeover (eg, most EcoBee, some Honeywell) use a `state` of `heat_cool` to automatically switch between heat and AC based on temperature, with the same `target_temp_low` and `target_temp_high` fields.

In this case, bubble card is still broken.

It isn't obvious how to fix this; I think the only solution is to show two temperature fields, like the native Tile card does:

![image](https://github.com/user-attachments/assets/23a00e98-c929-45e8-8914-8771e960e2b4)

Alternatively, you could use a layout like `- 70/74 +`, and have the `-` and `+` buttons modify _both_ setpoints.

At the very least, can you please hide the `- +` buttons when there are two setpoints and the state is `heat_cool`? Right now, clicking them raises an error and sets the thermostat to 0 (!!!)

Confusingly, my Samsung minisplit with autochangeover only uses a single `temperature` field in the same `heat_cool` state.

**Comment by Clooos** [comment]
Thank you @SLaks for the details, indeed the tile card seems like a nice layout for that case, the only downside is that I don't know if I can keep these as sub-buttons. 

I still need more tinkering on that, I really want to makes it the more compact it can be.

**Comment by Clooos** [comment]
Hi everyone! I've made some progress, I had to change (a lot) how it looks but I really like it! Can anyone try this version?

<img width="576" alt="image" src="https://github.com/user-attachments/assets/4a529d31-5913-4818-8699-b453503d5ce4">

To install this version, you need to remove Bubble Card from HACS first, then install it with the "[Without HACS](https://github.com/Clooos/Bubble-Card?tab=readme-ov-file#installation)" method.

[bubble-card.js.zip](https://github.com/user-attachments/files/17719857/bubble-card.js.zip)

Once installed, clear your cache then check in the editor if you see v2.3.0-beta.5.

You will need to remove your previous climate card then create a new one.

I can't wait for your feedback! 🤞

**Comment by SLaks** [comment]
I didn't try it, but that looks great! 

One suggestion: Swap the two setpoints so you revert them as lower, upper from left to right. (Like my Tile card screenshot) 

Thanks!

**Comment by cromelex** [comment]
> Hi everyone! I've made some progress, I had to change (a lot) how it looks but I really like it! Can anyone try this version?
> <img alt="image" width="576" src="https://private-user-images.githubusercontent.com/36499953/385374929-4a529d31-5913-4818-8699-b453503d5ce4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE0MzE2MDEsIm5iZiI6MTczMTQzMTMwMSwicGF0aCI6Ii8zNjQ5OTk1My8zODUzNzQ5MjktNGE1MjlkMzEtNTkxMy00ODE4LTg2OTktYjQ1MzUwM2Q1Y2U0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTEyVDE3MDgyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ3NjVlY2U2NTA5NDAxMjNhNWU0ODBhZjM2NzA0MDljODczNDI3YjhhM2UzNDVlY2YzYjAwOWY0NGMwYTRmN2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Y8DzHqjWpqhlEBzFBMv8G92pIxxVIYJfzYIzmiT3W5o">
> 
> To install this version, you need to remove Bubble Card from HACS first, then install it with the "[Without HACS](https://github.com/Clooos/Bubble-Card?tab=readme-ov-file#installation)" method.
> 
> [bubble-card.js.zip](https://github.com/user-attachments/files/17719857/bubble-card.js.zip)
> 
> Once installed, clear your cache then check in the editor if you see v2.3.0-beta.5.
> 
> You will need to remove your previous climate card then create a new one.
> 
> I can't wait for your feedback! 🤞

Unfortunately the +/- buttons still do not work.
I get the below error upon clicking.
![image](https://github.com/user-attachments/assets/a302a094-6183-4fe9-a4fb-c385104b7df7)

The editor is showing v2.3.0-beta.5. and I did open a new private window to make sure it wasn't something cashed. This is after creating a new card.

![image](https://github.com/user-attachments/assets/12d90662-07f4-4c04-b081-e87fc629c53f)

I'd also love to be able to hide the right hand side setpoints entirely  Is there a way to do it with .css ?
And is `.bubble-high-temp-container` the correct one?

**Comment by cromelex** [comment]
For clarity, here are the entity attributes that actually exist in Home-Assistant for this thermostat:

```
hvac_modes: off, heat, cool
min_temp: 4.5
max_temp: 30
target_temp_step: 0.5
current_temperature: 21.7
target_temp_high: 27
target_temp_low: 20.5
hvac_action: idle
friendly_name: Thermostat 0
```

**Comment by Clooos** [comment]
I should have fixed it!

[bubble-card.js.zip](https://github.com/user-attachments/files/17721109/bubble-card.js.zip)

**Comment by cromelex** [comment]
I will try later today or early tomorrow and will provide feedback.

**Comment by cromelex** [comment]
@Clooos  can confirm that fixed it, both the heating and cooling setpoints are now working as expected.
Adding screenshot just to show both values changing in the mushroom climate card as well.

![image](https://github.com/user-attachments/assets/7f5157b3-0088-4f83-9608-7f3f7ce7d162)

Thank you for this!

**Comment by Clooos** [comment]
Finally! 🎉

Thank you again for testing it! Just a few issues left to fix, then I will be able to release the next and hopefully last v2.3.0 beta! 🤞

**Comment by cromelex** [comment]
@klatka 
You can do this with CSS, see my example above.

Just paste this code snippet in the custom style template for the the thermostat card where you want to hide it

```css
.bubble-high-temp-container {
  display: none;
}
```
![Screenshot_20241115-085638](https://github.com/user-attachments/assets/2ae14873-7597-49cb-b6ec-8e08a2845f93)

This is what mine look like at the moment
![Screenshot_20241115-085851](https://github.com/user-attachments/assets/51052124-5b92-408d-8f3c-20b0b02aa5b4)

**Comment by klatka** [comment]
@cromelex  thank you! Now it looks like this (still a padding issue?):

![image](https://github.com/user-attachments/assets/5ff51328-2dc7-49cf-bb95-1d9578ff4cb2)

**Comment by cromelex** [comment]
I think that happened to me first as well. I think it might be just caching issues?
Try to clear the cache.
After I cleared the cache it didn't happen again (I had to restart my wall tablet for it to fully clear).

**Comment by klatka** [comment]
I just noticed that there is no delay when setting a temperature. When fast-clicking multiple times on + there should be only one service call

**Comment by Clooos** [comment]
Everything should work as expected now! 🤞

@klatka There is now a delay 👌

@cromelex and @klatka It is now possible to hide target temperatures in the editor.

https://github.com/Clooos/Bubble-Card/releases/tag/v2.3.0-beta.7

**Comment by cromelex** [comment]
Thank you for this, I'll give it a try when I have a moment.

**Comment by cromelex** [comment]
@Clooos  with 2.3.0-beta7 the climate card is not showing at all? Neither old cards, nor the option in the editor to add it.

Rolling back to beta6 makes them show up again.

**Comment by Clooos** [comment]
This is a really weird issue, but you are not the first. Take a look at this:

https://github.com/Clooos/Bubble-Card/issues/921

**Comment by cromelex** [comment]
Ah this is so weird.

So I had the issue with beta7, installed via HACS.
Redownloaded and went to beta6, that fixed the missing climate card. 
Redownloaded beta7, cleared cache... and now it is showing up again.


But yes the new hide toggle is working for me, and there seem to be no other issues with the card. Thanks!

**Comment by klatka** [comment]
Beta 7 looks good to me 👍🏼
